spring.application.name=DA2Back
spring.datasource.url=jdbc:mysql://localhost:3306/marketplace
spring.datasource.driverClassName=com.mysql.jdbc.Driver
spring.datasource.username= 
spring.datasource.password= 
spring.jpa.hibernate.ddl-auto= update
jwt.secret=MiSuperClaveSecreta123456789012345678901234567890
jwt.expiration=3600000 

# Credenciales del admin que se crea automáticamente al arrancar la app
admin.seed.username=admin
admin.seed.email=admin@da2back.com
admin.seed.password=CambiarEstaClave123