spring.application.name=DA2Back
spring.datasource.url=jdbc:mysql://localhost:3306/marketplace
spring.datasource.driverClassName=com.mysql.jdbc.Driver
spring.datasource.username= 
spring.datasource.password= 
spring.jpa.hibernate.ddl-auto= update
application.security.jwt.secretKey=MiSuperClaveSecreta123456789012345678901234567890
application.security.jwt.expiration=3600000 